//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum eCommand { 
	CreateCocktailCommand = 0, 
	DeleteCocktailCommand = 1, 
	CreateIngredientCommand = 2, 
	SetInitialStateCommand = 3
}
export enum eCommandType { 
	Create = 0, 
	Edit = 1, 
	Delete = 2
}
