//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum eCommand { 
	CreateCocktailCommand = 0, 
	EditCocktailCommand = 1, 
	RemoveCocktailCommand = 2, 
	CreateIngredientCommand = 3, 
	EditIngredientCommand = 4, 
	RemoveIngredientCommand = 5
}
export enum eCommandType { 
	None = 0, 
	Create = 1, 
	Edit = 2, 
	Remove = 4
}
