//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum eCommand { 
	CreateCocktailCommand = 0, 
	DeleteCocktailCommand = 1, 
	CreateIngredientCommand = 2, 
	EditIngredientCommand = 3, 
	RemoveIngredientCommand = 4
}
export enum eCommandType { 
	None = 0, 
	Create = 1, 
	Edit = 2, 
	Delete = 4
}
