//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { eCommandType } from './enums';
import { eCommand } from './enums';

export interface IBaseDto
{
	id: string;
	entityStatus: number;
	createdOn: any;
}
export interface IAppEventDto extends IBaseDto
{
	arguments: string;
	commandCode: number;
	commandType: eCommandType;
}
export interface ICocktailDto extends IBaseDto
{
	name: string;
	excerpts: IRecipeExcerptDto[];
}
export interface IIngredientDto extends IBaseDto
{
	name: string;
	strength: number;
	excerpts: IRecipeExcerptDto[];
}
export interface IRecipeExcerptDto extends IBaseDto
{
	cocktailId: string;
	ingredientId: string;
	amount: number;
}
export interface ICommandInfo<TDto>
{
	command: eCommand;
	commandType: eCommandType;
	dto: TDto;
}
