//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface ICocktailDto
{
	name: string;
	strength: number;
	ingredients: IIngredientDto[];
}
export interface IIngredientDto
{
	cocktailId: string;
	name: string;
	amount: number;
	unitOfMeasure: string;
}
