//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface IBaseDto
{
	id: string;
}
export interface IAppEventDto extends IBaseDto
{
	arguments: string;
	commandCode: number;
}
export interface ICocktailDto extends IBaseDto
{
	name: string;
	strength: number;
	ingredients: IIngredientDto[];
}
export interface IIngredientDto extends IBaseDto
{
	cocktailId: string;
	name: string;
	amount: number;
	unitOfMeasure: string;
}
