//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

module NetCoreCQRSdemo.Domain.Dtos {
	export interface ICocktailDto
	{
		name: string;
		strength: number;
		ingredients: NetCoreCQRSdemo.Domain.Dtos.IIngredientDto[];
	}
	export interface IIngredientDto
	{
		cocktailId: string;
		name: string;
		amount: number;
		unitOfMeasure: string;
	}
}
